### PR TITLE
🔎

### PR DESCRIPTION
**Pull request by marcesher**
1) changes github-my-issues to add additional help for creating an oauth token for github

2) changes start.sh to add "/" as an alias and extract the bot name into
an environment variable

3) adds a new "cfpbsearch.coffee" script that searches our running
instance of https://github.com/cfpb/github-wiki-search. This enables
commands such as `hubot search [term]` and `hubot search wiki [term]`.
Pagination is achieved with `hubot search next`

### CODE REVIEW

**Comment by contolini** [comment]
@marcesher After making the minor edit above, please squash your commits into a single emoji per the [contributing guidelines](https://github.com/cfpb/CFPBot#contributing) and then this thing is good-to-go. I'm writing a PR for the internal repo as we speak.

**Comment by contolini** [comment]
Additional thought: Why not call it `github-wiki-search.coffee` instead of `cfpbsearch.coffee`?

**Comment by marcesher** [comment]
@contolini good question re: the name of the thing. It's because `github-wiki-search` is itself no longer accurate. It searches a lot more than just wikis now. I didn't want to perpetuate that misnomer.

**Comment by marcesher** [comment]
@contolini "...please squash your commits into a single emoji ..."

:rage: :rage1: :rage2: :rage3: :rage4: 

That's what I think about your contributing requirement.

**Comment by contolini** [comment]
@marcesher That's five emojis.

**Comment by contolini** [comment]
:rose:

**Comment by anselmbradford** [comment]
Can we just re-write this thing in [4Lang](https://github.com/4Lang/4)?

**Comment by contolini** [comment]
@anselmbradford theregoesmyregroup

**Comment by anselmbradford** [comment]
@contolini I look forward to the charades lightning talk on how you handled api calls.

**Pull request merged**
