### PR TITLE
👁

### PR DESCRIPTION
**Pull request by marcesher**
Adds a function to search for Google Drive files

### CODE REVIEW

**Comment by Scotchester** [comment]
1. I object to the command being `collab`, but I've probably lost that war.
2. Will this work after it gets "shut down" tomorrow?

**Comment by marcesher** [comment]
@Scotchester I'm happy to change the command, or make it multi-command. I have zero strong opinion on this. What would you recommend?

It'll work because it's completely decoupled from google drive itself

**Comment by Scotchester** [comment]
> @Scotchester I'm happy to change the command, or make it multi-command. I have zero strong opinion on this. What would you recommend?

It's tricky. From a clear "command invocation" naming perspective, I guess I'd want something like `hubot google-drive-search`, but that is almost certainly harder to remember, which makes it a barrier to use. Maybe just `hubot gdrive`?

Might be worth polling the team.

**Comment by Scotchester** [comment]
> It'll work because it's completely decoupled from google drive itself

Yeah, I realized this after you posted in chat. Good stuff :+1:

**Comment by marcesher** [comment]
@Scotchester I added `gdrive`

**Review by Scotchester — APPROVED** [review]
Let's give it a whirl :+1:

**Pull request merged**
