### PR TITLE
:diamond_shape_with_a_dot_inside:

### PR DESCRIPTION
**Pull request by marcesher**
To simplify command running:

`. help` vs `CFPBot help`, eg

### CODE REVIEW

**Comment by higs4281** [comment]
👍 man, I love this alias. i could not type 'cfpbot' to save my life.

**Comment by contolini** [comment]
How do y'all feel about "please" instead of "." as an alias? It makes it a little more human.

`please help`
`please define PMO`
`please animate me kittens`

**Comment by marcesher** [comment]
I feel no need to be more human to a bot. 

On a more serious note, though, that could become problematic because people actually do start sentences with the word "please". So in conversation, if someone said something, and then another person responded "please help"... that'd be weird.

I'm not violently opposed to it or anything... I kind of like it. But I also appreciate the efficiency of "." for purposes of running bot commands

**Comment by jonathanwcrane** [comment]
+1 to marc.  Though I would like to maintain cfpbot as an alias as well to make it more explicit.

**Comment by contolini** [comment]
@jonathanwcrane Unfortunately hubot only allows a single alias. Currently its name is `Molliebot` with an alias of `cfpbot` so either works. This PR would change it to `Molliebot` with an alias of `.`

**Comment by marcesher** [comment]
This also returns it to the behavior of the previous chat server, where we addressed the bot by either the `/` alias or the honorary name (like Molliebot). "cfpbot" has never been an established thing, and I agree with Bill... it's unweildy

**Comment by willbarton** [comment]
I kind of prefer `please`, to be honest.

How difficult would it be to add support for multiple aliases?

**Comment by jonathanwcrane** [comment]
I think please is good but it's not so different that it won't cause unexpected behavior.

**Comment by Scotchester** [comment]
`please` is a non-starter for the reason Marc stated: People start actual sentences with it.

**Comment by willbarton** [comment]
Please, @Scotchester.

**Comment by contolini** [comment]
I just searched our Mattermost logs for "please" and I only see one instance of someone starting a statement with it.

In fact, @imuchnik once failed to get Molliebot to perform a command (she said `Mollie` instead of `Molliebot` and she followed up with: "Mollie, please"). "Please" seems intuitive to me.

We used to alias it to "/" and no one except Marc used that alias. I see the same thing happening with "." I *hope* people occasionally accidentally trigger the bot by starting sentences with "please" because it will remind folks that the bot has an alias.

**Comment by willbarton** [comment]
☝️ I never knew it was aliased to `/`, and the old ircer in my rebels against anything that's not my client responding to `/`.

**Comment by Scotchester** [comment]
@contolini I like the spirit and intent, but I think you'll annoy people if they try to write "Please …" as a regular message and get back bot responses.

I suppose we could try it for a bit and see how it goes.

**Comment by willbarton** [comment]
I'm recommending the boringest of boring: `bot`

**Comment by marcesher** [comment]
how about `sudo`

I also like `guvnah` 

`please` and `bot` are fine too. I don't feel strongly enough about any of them to argue.

**Comment by contolini** [comment]
Let's try 'em all and see which one works best. For science. See #35.

**Pull request closed without merging**
